### ISSUE TITLE
Token generation

### ISSUE THREAD

**Issue by EthanOKung** [codesoap/mycolog#1]
Awesome program.  I'm posting a feature request - would be cool to allow the user to generate their own token for each entry since people may already have a naming system in place for their cultures.

**Comment by codesoap** [comment]
Thanks for the feedback! I'm glad to hear someone besides me is using mycolog.

As you have guessed already, this is not a feature I'm too keen on adding. I could think about making the tokens editable, but this would come with the risk, that people would misunderstand this field and misuse it. For now, I'd prefer to keep things simple.

**Comment by EthanOKung** [comment]
Yep certainly makes sense.  Auto-generation token is nice and should not be removed, but making it editable would provide flexibility, though I can see you would need to put in a lot of checks for invalid/duplicate tokens.  I'm just thinking that some people may want to label things their own way so the option to not have to add another label could be nice, but not a big deal.
