### ISSUE TITLE
Data storage location

### ISSUE THREAD

**Issue by EthanOKung** [codesoap/mycolog#2]
Would be great to include in the documentations where the log data is stored, so that users can make backup and/or delete/switch databases

**Comment by codesoap** [comment]
Good idea! I have put some info into the README for now: https://github.com/codesoap/mycolog/commit/345cd2d10531fb2e15bef1c32f2f5ad82e4f2112 . If I implement a `--help` flag in the future or similar, I might put the info in there as well.

**Comment by EthanOKung** [comment]
Awesome!  Very useful!
