### ISSUE TITLE
Compilation notes

### ISSUE THREAD

**Issue by EthanOKung** [codesoap/mycolog#4]
Sharing a compilation note for Windows OS FYI:

Need to first enabled CGO in cmd prompt with command
>> set CGO_ENABLED=1

Also watch out to make sure your GO compiler and GCC compiler are the same bit depth (32 vs 64).  I wasn't paying attention to that and had to reinstall a different version of GO compiler.

On an unrelated note — I wanted the program to display all cultures without needing to manually set the 30 day filter, so I just changed line 110 in "queries.go" to

if filter.Since == nil {

It works perfectly for my purpose but is definitely a hack.  If there is another easy way to flip the 30 day flag that is more "proper", please let me know  ;)

**Comment by codesoap** [comment]
When I compiled on Windows, I didn't have to enable cgo manually. As far as I'm aware, it is on by default. Could it be that you had switched it off yourself at some point in the past?

----

If you want to view e.g. mycelium that is older than 30 days by default, this patch should work:
```patch
diff --git a/cmd/mycolog/tmpl/details.html b/cmd/mycolog/tmpl/details.html
index 174c226..58bc4f1 100644
--- a/cmd/mycolog/tmpl/details.html
+++ b/cmd/mycolog/tmpl/details.html
@@ -15,7 +15,7 @@
 {{if .Grow}}{{$typeName   = "Grow"}}{{end}}
 {{$backLink := ""}}
 {{if .Spores}}{{$backLink = "/spores"}}{{end}}
-{{if .Myc}}{{$backLink    = "/mycelium"}}{{end}}
+{{if .Myc}}{{$backLink    = "/mycelium?old=on"}}{{end}}
 {{if .Spawn}}{{$backLink  = "/spawn"}}{{end}}
 {{if .Grow}}{{$backLink   = "/grows"}}{{end}}
 {{$createdAtLabel := ""}}
diff --git a/cmd/mycolog/tmpl/overview.html b/cmd/mycolog/tmpl/overview.html
index fd466c4..a3944aa 100644
--- a/cmd/mycolog/tmpl/overview.html
+++ b/cmd/mycolog/tmpl/overview.html
@@ -10,7 +10,7 @@
                                <a href="/spores" class="pure-menu-link">Spores</a>
                        </li>
                        <li class="pure-menu-item{{if .MycSelected}} pure-menu-selected{{end}}">
-                               <a href="/mycelium" class="pure-menu-link">Mycelium</a>
+                               <a href="/mycelium?old=on" class="pure-menu-link">Mycelium</a>
                        </li>
                        <li class="pure-menu-item{{if .SpawnSelected}} pure-menu-selected{{end}}">
                                <a href="/spawn" class="pure-menu-link">Spawn</a>
```

**Comment by EthanOKung** [comment]
I had never installed GO or GCC compiler on this machine until now, and I rarely do code compilation here (I think the only things I've comiled on this machine were a few small python and java codes), so pretty sure I hadn't change the setting before...

Your patch worked great, thanks — definitely less hackish than my method, hah.
