### ISSUE TITLE
Creation date check does not allow for same day child component creation

### ISSUE THREAD

**Issue by bblough** [codesoap/mycolog#7]
Hi,

I was playing around with the app, and so far I like it.  I'm very interested to see how it evolves.

However, when trying to create a child component with the same date as the parent, it produces the error "An error occurred: a parent was not created before the new component."

Obviously it makes sense to expect that a parent component is created before its child component.  But with date granularity being a whole day, that means you can't log a parent and child with the same create/acquisition date.   Since transitioning between steps usually takes time, this would normally be OK.  But this ignores the cases where you acquire a component from an external source, and on the same day, move to the next step.  For example, acquiring spores and immediately creating streak plates, or acquiring LC and immediately putting it to agar or grain.

Or maybe other people don't do this and I'm just impatient ;-)

Anyway, I think the date granularity is fine - I think logging actual times would detract from the UX.  But I think it would be good to relax the check to allow same-day rather than strictly before/after.

**Comment by bblough** [comment]
I'm sure you've put way more thought into this than I have, so I'm really just thinking out loud here...  But wWould it make sense to do the graph layout based strictly on parent/child relationships, rather than date?  Would that cause problems when combining two lineages? (e.g., crossing spores from two different genetic lines).

**Comment by codesoap** [comment]
What you describe is the bevhavior that was initially implemented. Somewhat recently, in https://github.com/codesoap/mycolog/commit/d5bb3b98a2e8f13e46d0eda995fc55dd4c065c25, I introduced the change, that the all components of the same date are displayed at the same "height" in graphs.

I did this, because I didn't like that some components were displayed a lot higher in the graph, even though they were younger than most components that were lower in the graph. But it's only a crude approximation to what I really wanted to do: Ideally I could just enforce chronological ordering in the graphs, but I have found no good way to achieve this with the given tool (Graphviz).

Maybe you're right and I should remove the workaround for now and look for a better solution - maybe one without Graphviz - long term.

**Comment by bblough** [comment]
Ah, I see.  I'm certainly no GraphViz expert, but it seems like what you're doing is more or less "the  way" to enforce chronological  ordering. (though if you wanted strict chronological ordering, with different dates forced to separate ranks in all cases, you'd likely need to introduce some invisible nodes/edges to get that).

What do you think about using the current chronological ordering, but not setting the rank if a parent/child have the same date? It's a bit of a naive solution, but this should give the current behavior if the dates are different, or if nodes are not parent/child of each other, and should avoid putting nodes with the same date at the same rank if it's a parent/child.  Though there are likely some edge cases that I haven't considered.

I've made changes to this effect locally, and have played around with it a bit.  I don't think it's a perfect solution by any means, but so far it seems OK to the extent that I've tested it.  I could submit a PR with my changes if you'd like to play with it. (With the caveat that my knowledge of Go is almost zero).
![myco](https://github.com/user-attachments/assets/a10e222a-ca4c-4cab-bcdc-fe2479ed06dc)

**Comment by codesoap** [comment]
Inspired by our conversation I have now re-investigated the issue and actually found a solution to enforce strict chronologic ordering in the graphs at https://stackoverflow.com/a/2272412/6026166. I have implemented it in 5293384b480d877e441019827163ca0951d73a7c. I'm now pretty happy with the solution and don't consider it a workaround anymore.

I have now given your suggestion some thought, but don't like that components of different creation dates are displayed on the same rank. I don't think this can be avoided, when there are nodes without a specified rank.

Thus I prefer the simplest solution for now: I'll just accept, that sometimes parent and child are placed on the same rank. It should be a rare scenario, so I don't think it will be too irritating. I have implemented the change in 8b8ab831c2871fe6bf99e5f5c1a786d318e0ae61.

Let me know, if you foresee problems with this approach.

**Comment by bblough** [comment]
Ah, I see you went with strict ordering after all.

With my test database, I get the following:
![myco1](https://github.com/user-attachments/assets/ba57933f-05dc-440f-91c8-218b7bb2bec2)

Which is... not ideal.

I see what you mean about not specifying ranks causing components with different dates being on the same rank.  I agree this isn't ideal, either.

But rather than not setting a rank, what about forcing an intermediate rank for the children that have the same date as their parent?

If I do that, I get:
![myco3](https://github.com/user-attachments/assets/313a792b-4a76-4be1-aaef-5975ad1b843b)

So children that have the same date as their parent get put on a separate row (with only components from that date), but everything else is still strictly ordered by date.  Components with different dates are always on different ranks, and components with the same date may be on the same rank or on consecutive ranks, depending on the parent/child relationships.

It seems like this could be the best of both worlds.

**Comment by codesoap** [comment]
Thanks for your thorough investigation. I agree, that the graph does not look great in your example. I would have expected Graphviz to at least put `181M` and `U795` to the left of `Y3UT`. I guess Graphviz is not well optimized for scenarios where nodes are forced onto the same rank.

The solution you propose looks a lot nicer. However, I feel like implementing it would complicate the algorithm significantly and I still view these scenarios as rare edge cases. For now, I would thus prefer to leave things as they are. If you feel like it's not that difficult and you can achieve the improvement with a small patch, feel free to show me in a PR and maybe I'll reconsider my stance.

**Comment by bblough** [comment]
I don't think it's a big or complicated change, but of course, it's ultimately your decision.  I've opened PR #8 for you consideration.
